//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePubIntegrator.ServiceReference_ePubCloud {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserContract", Namespace="http://schemas.datacontract.org/2004/07/ServiceePubLibrary")]
    [System.SerializableAttribute()]
    public partial class UserContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_ePubCloud.IServiceePubLibrary")]
    public interface IServiceePubLibrary {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/RegisterUser", ReplyAction="http://tempuri.org/IServiceePubLibrary/RegisterUserResponse")]
        void RegisterUser(string xmlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/RegisterUser", ReplyAction="http://tempuri.org/IServiceePubLibrary/RegisterUserResponse")]
        System.Threading.Tasks.Task RegisterUserAsync(string xmlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/Login", ReplyAction="http://tempuri.org/IServiceePubLibrary/LoginResponse")]
        bool Login(string xmlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/Login", ReplyAction="http://tempuri.org/IServiceePubLibrary/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string xmlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetUser", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetUserResponse")]
        ePubIntegrator.ServiceReference_ePubCloud.UserContract GetUser(string xmlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetUser", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetUserResponse")]
        System.Threading.Tasks.Task<ePubIntegrator.ServiceReference_ePubCloud.UserContract> GetUserAsync(string xmlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/SetUserInfo", ReplyAction="http://tempuri.org/IServiceePubLibrary/SetUserInfoResponse")]
        void SetUserInfo(string xmlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/SetUserInfo", ReplyAction="http://tempuri.org/IServiceePubLibrary/SetUserInfoResponse")]
        System.Threading.Tasks.Task SetUserInfoAsync(string xmlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetUserInfo", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetUserInfoResponse")]
        string GetUserInfo(string xmlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetUserInfo", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetUserInfoResponse")]
        System.Threading.Tasks.Task<string> GetUserInfoAsync(string xmlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetMostActiveDay", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetMostActiveDayResponse")]
        string GetMostActiveDay();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetMostActiveDay", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetMostActiveDayResponse")]
        System.Threading.Tasks.Task<string> GetMostActiveDayAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetMostActiveMonth", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetMostActiveMonthResponse")]
        string GetMostActiveMonth();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetMostActiveMonth", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetMostActiveMonthResponse")]
        System.Threading.Tasks.Task<string> GetMostActiveMonthAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetMostActiveYear", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetMostActiveYearResponse")]
        string GetMostActiveYear();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetMostActiveYear", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetMostActiveYearResponse")]
        System.Threading.Tasks.Task<string> GetMostActiveYearAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetChaptersTopFive", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetChaptersTopFiveResponse")]
        string GetChaptersTopFive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetChaptersTopFive", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetChaptersTopFiveResponse")]
        System.Threading.Tasks.Task<string> GetChaptersTopFiveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetAllMonths", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetAllMonthsResponse")]
        string GetAllMonths();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetAllMonths", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetAllMonthsResponse")]
        System.Threading.Tasks.Task<string> GetAllMonthsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetMostActiveDayByUser", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetMostActiveDayByUserResponse")]
        string GetMostActiveDayByUser(string xmlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetMostActiveDayByUser", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetMostActiveDayByUserResponse")]
        System.Threading.Tasks.Task<string> GetMostActiveDayByUserAsync(string xmlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetMostActiveMonthByUser", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetMostActiveMonthByUserResponse")]
        string GetMostActiveMonthByUser(string xmlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetMostActiveMonthByUser", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetMostActiveMonthByUserResponse")]
        System.Threading.Tasks.Task<string> GetMostActiveMonthByUserAsync(string xmlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetMostActiveYearByUser", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetMostActiveYearByUserResponse")]
        string GetMostActiveYearByUser(string xmlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetMostActiveYearByUser", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetMostActiveYearByUserResponse")]
        System.Threading.Tasks.Task<string> GetMostActiveYearByUserAsync(string xmlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetAllMonthsByUser", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetAllMonthsByUserResponse")]
        string GetAllMonthsByUser(string xmlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetAllMonthsByUser", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetAllMonthsByUserResponse")]
        System.Threading.Tasks.Task<string> GetAllMonthsByUserAsync(string xmlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetTop5EpubFav", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetTop5EpubFavResponse")]
        string GetTop5EpubFav();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetTop5EpubFav", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetTop5EpubFavResponse")]
        System.Threading.Tasks.Task<string> GetTop5EpubFavAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetTop5EpubBookmark", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetTop5EpubBookmarkResponse")]
        string GetTop5EpubBookmark();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetTop5EpubBookmark", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetTop5EpubBookmarkResponse")]
        System.Threading.Tasks.Task<string> GetTop5EpubBookmarkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetTop5EpubFavByUser", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetTop5EpubFavByUserResponse")]
        string GetTop5EpubFavByUser(string xmlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetTop5EpubFavByUser", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetTop5EpubFavByUserResponse")]
        System.Threading.Tasks.Task<string> GetTop5EpubFavByUserAsync(string xmlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetTop5EpubBookmarkByUser", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetTop5EpubBookmarkByUserResponse")]
        string GetTop5EpubBookmarkByUser(string xmlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubLibrary/GetTop5EpubBookmarkByUser", ReplyAction="http://tempuri.org/IServiceePubLibrary/GetTop5EpubBookmarkByUserResponse")]
        System.Threading.Tasks.Task<string> GetTop5EpubBookmarkByUserAsync(string xmlString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceePubLibraryChannel : ePubIntegrator.ServiceReference_ePubCloud.IServiceePubLibrary, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceePubLibraryClient : System.ServiceModel.ClientBase<ePubIntegrator.ServiceReference_ePubCloud.IServiceePubLibrary>, ePubIntegrator.ServiceReference_ePubCloud.IServiceePubLibrary {
        
        public ServiceePubLibraryClient() {
        }
        
        public ServiceePubLibraryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceePubLibraryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceePubLibraryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceePubLibraryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegisterUser(string xmlString) {
            base.Channel.RegisterUser(xmlString);
        }
        
        public System.Threading.Tasks.Task RegisterUserAsync(string xmlString) {
            return base.Channel.RegisterUserAsync(xmlString);
        }
        
        public bool Login(string xmlString) {
            return base.Channel.Login(xmlString);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string xmlString) {
            return base.Channel.LoginAsync(xmlString);
        }
        
        public ePubIntegrator.ServiceReference_ePubCloud.UserContract GetUser(string xmlString) {
            return base.Channel.GetUser(xmlString);
        }
        
        public System.Threading.Tasks.Task<ePubIntegrator.ServiceReference_ePubCloud.UserContract> GetUserAsync(string xmlString) {
            return base.Channel.GetUserAsync(xmlString);
        }
        
        public void SetUserInfo(string xmlString) {
            base.Channel.SetUserInfo(xmlString);
        }
        
        public System.Threading.Tasks.Task SetUserInfoAsync(string xmlString) {
            return base.Channel.SetUserInfoAsync(xmlString);
        }
        
        public string GetUserInfo(string xmlString) {
            return base.Channel.GetUserInfo(xmlString);
        }
        
        public System.Threading.Tasks.Task<string> GetUserInfoAsync(string xmlString) {
            return base.Channel.GetUserInfoAsync(xmlString);
        }
        
        public string GetMostActiveDay() {
            return base.Channel.GetMostActiveDay();
        }
        
        public System.Threading.Tasks.Task<string> GetMostActiveDayAsync() {
            return base.Channel.GetMostActiveDayAsync();
        }
        
        public string GetMostActiveMonth() {
            return base.Channel.GetMostActiveMonth();
        }
        
        public System.Threading.Tasks.Task<string> GetMostActiveMonthAsync() {
            return base.Channel.GetMostActiveMonthAsync();
        }
        
        public string GetMostActiveYear() {
            return base.Channel.GetMostActiveYear();
        }
        
        public System.Threading.Tasks.Task<string> GetMostActiveYearAsync() {
            return base.Channel.GetMostActiveYearAsync();
        }
        
        public string GetChaptersTopFive() {
            return base.Channel.GetChaptersTopFive();
        }
        
        public System.Threading.Tasks.Task<string> GetChaptersTopFiveAsync() {
            return base.Channel.GetChaptersTopFiveAsync();
        }
        
        public string GetAllMonths() {
            return base.Channel.GetAllMonths();
        }
        
        public System.Threading.Tasks.Task<string> GetAllMonthsAsync() {
            return base.Channel.GetAllMonthsAsync();
        }
        
        public string GetMostActiveDayByUser(string xmlString) {
            return base.Channel.GetMostActiveDayByUser(xmlString);
        }
        
        public System.Threading.Tasks.Task<string> GetMostActiveDayByUserAsync(string xmlString) {
            return base.Channel.GetMostActiveDayByUserAsync(xmlString);
        }
        
        public string GetMostActiveMonthByUser(string xmlString) {
            return base.Channel.GetMostActiveMonthByUser(xmlString);
        }
        
        public System.Threading.Tasks.Task<string> GetMostActiveMonthByUserAsync(string xmlString) {
            return base.Channel.GetMostActiveMonthByUserAsync(xmlString);
        }
        
        public string GetMostActiveYearByUser(string xmlString) {
            return base.Channel.GetMostActiveYearByUser(xmlString);
        }
        
        public System.Threading.Tasks.Task<string> GetMostActiveYearByUserAsync(string xmlString) {
            return base.Channel.GetMostActiveYearByUserAsync(xmlString);
        }
        
        public string GetAllMonthsByUser(string xmlString) {
            return base.Channel.GetAllMonthsByUser(xmlString);
        }
        
        public System.Threading.Tasks.Task<string> GetAllMonthsByUserAsync(string xmlString) {
            return base.Channel.GetAllMonthsByUserAsync(xmlString);
        }
        
        public string GetTop5EpubFav() {
            return base.Channel.GetTop5EpubFav();
        }
        
        public System.Threading.Tasks.Task<string> GetTop5EpubFavAsync() {
            return base.Channel.GetTop5EpubFavAsync();
        }
        
        public string GetTop5EpubBookmark() {
            return base.Channel.GetTop5EpubBookmark();
        }
        
        public System.Threading.Tasks.Task<string> GetTop5EpubBookmarkAsync() {
            return base.Channel.GetTop5EpubBookmarkAsync();
        }
        
        public string GetTop5EpubFavByUser(string xmlString) {
            return base.Channel.GetTop5EpubFavByUser(xmlString);
        }
        
        public System.Threading.Tasks.Task<string> GetTop5EpubFavByUserAsync(string xmlString) {
            return base.Channel.GetTop5EpubFavByUserAsync(xmlString);
        }
        
        public string GetTop5EpubBookmarkByUser(string xmlString) {
            return base.Channel.GetTop5EpubBookmarkByUser(xmlString);
        }
        
        public System.Threading.Tasks.Task<string> GetTop5EpubBookmarkByUserAsync(string xmlString) {
            return base.Channel.GetTop5EpubBookmarkByUserAsync(xmlString);
        }
    }
}
