//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceePubLibraryEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chapter
    {
        public Chapter()
        {
            this.ChapterBookmark = new HashSet<ChapterBookmark>();
            this.ChapterFav = new HashSet<ChapterFav>();
        }
    
        public int Id { get; set; }
        public int Epub_Id { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<ChapterBookmark> ChapterBookmark { get; set; }
        public virtual ICollection<ChapterFav> ChapterFav { get; set; }
        public virtual Epub Epub { get; set; }
    }
}
