//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceePubLibraryEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Epub
    {
        public Epub()
        {
            this.Chapter = new HashSet<Chapter>();
            this.EpubBookmark = new HashSet<EpubBookmark>();
            this.EpubFav = new HashSet<EpubFav>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Subject { get; set; }
    
        public virtual ICollection<Chapter> Chapter { get; set; }
        public virtual ICollection<EpubBookmark> EpubBookmark { get; set; }
        public virtual ICollection<EpubFav> EpubFav { get; set; }
    }
}
