//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceePubLibraryEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model_Service_ePub_LibraryContainer : DbContext
    {
        public Model_Service_ePub_LibraryContainer()
            : base("name=Model_Service_ePub_LibraryContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> User { get; set; }
        public DbSet<Chapter> Chapter { get; set; }
        public DbSet<ChapterBookmark> ChapterBookmark { get; set; }
        public DbSet<ChapterFav> ChapterFav { get; set; }
        public DbSet<Epub> Epub { get; set; }
        public DbSet<EpubBookmark> EpubBookmark { get; set; }
        public DbSet<EpubFav> EpubFav { get; set; }
        public DbSet<LoginHistory> LoginHistory { get; set; }
    }
}
