//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceePubLibraryEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ChapterBookmark = new HashSet<ChapterBookmark>();
            this.ChapterFav = new HashSet<ChapterFav>();
            this.EpubBookmark = new HashSet<EpubBookmark>();
            this.EpubFav = new HashSet<EpubFav>();
            this.LoginHistory = new HashSet<LoginHistory>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string Salt { get; set; }
    
        public virtual ICollection<ChapterBookmark> ChapterBookmark { get; set; }
        public virtual ICollection<ChapterFav> ChapterFav { get; set; }
        public virtual ICollection<EpubBookmark> EpubBookmark { get; set; }
        public virtual ICollection<EpubFav> EpubFav { get; set; }
        public virtual ICollection<LoginHistory> LoginHistory { get; set; }
    }
}
